version: "3"
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: test-runner
    environment:
      - ELASTICSEARCH_TEST_URL=http://elasticsearch:9200
    command:
      [
        "go",
        "test",
        "-mod=readonly",
        "-v",
        "-race",
        "-tags=integration",
        "./...",
      ]
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:5.3
    ports:
      - "9201:9200"
